services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    chain_command.manager:
        class: EugeneMoz\ChainCommandBundle\Service\ChainCommandManager

    EugeneMoz\ChainCommandBundle\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Command/'

    # Event Listener to prevent direct execution of member commands
    EugeneMoz\ChainCommandBundle\EventListener\PreventMemberExecutionListener:
        arguments:
            $manager: '@chain_command.manager'
            $container: '@service_container'
        tags:
            - { name: kernel.event_subscriber }
