services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    EugeneMoz\BarBundle\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection}'
