services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    EugeneMoz\FooBundle\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection}' 
